# Generated by Django 4.1.7 on 2023-03-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_rename_shippingaddres_shippingaddress"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[("C", "Completed"), ("P", "Pending"), ("F", "Failed")],
                default="P",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="inventory",
            field=models.IntegerField(null=True),
        ),
    ]
