# Generated by Django 4.1.7 on 2023-03-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_order_payment_status_product_inventory"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer", old_name="name", new_name="first_name",
        ),
        migrations.AddField(
            model_name="customer",
            name="last_name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
