# Generated by Django 4.1.7 on 2023-03-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_rename_name_customer_first_name_customer_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
